services:
  products:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/products"
      - "/opt/products/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true