import EditButton from "./edit-button"
export default function ProductList(){
    return(
        <div className="">
            <div className="me-5 ms-5">
                <table className="table table-striped py-2 table-danger">
                    <thead>
                        <tr className="border border-primary my-2">
                            <th>Product details</th>
                            <th>Price</th>
                            <th>Stock</th>
                            <th>Sku</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr className="border border-primary">
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr className="border border-primary">
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                        <tr>
                            <td>Silla</td>
                            <td>$1234</td>
                            <td>23</td>
                            <td>7892</td>
                            <td>
                                <EditButton></EditButton>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    )
}